"""
XDART-Φ × Dark Whisper Intelligence — Synthesis Engine
========================================================

DarkWhisperEngine is the analytical core of the dark intelligence layer.
It takes triaged dark signals and synthesizes them with clean perceptual
patterns to produce intelligence reports — Dark Whisper Syntheses.

THE SYNTHESIS PROCESS:

  INPUT: Triaged YES/MAYBE dark signals + Active clean patterns from ProactiveEngine

  STEP 1 — ENTITY/TOPIC OVERLAP DETECTION
    For each dark signal, compare its content against active clean patterns
    to find thematic/entity overlap. Overlap = same actors, domains, regions,
    or strategic themes present in both.

  STEP 2 — GAP DETECTION & CREATIVE NEXUS BRIDGE
    If a dark signal is relevant but the connection to clean patterns is unclear
    (the "gap"), the Creative Nexus (imagination engine) is invoked:
      • Targeted concept pairing: (dark_concept ↔ clean_concept)
      • LLM generates an imaginative hypothetical connection
      • Link is stored in MongoDB creative_links with tag="dark_whisper_gap"
      • Result is ALWAYS labeled SPECULATIVE in the output

  STEP 3 — LLM SYNTHESIS
    LLM synthesizes: clean_evidence + dark_signal + (optional imagination link)
    → produces a Dark Whisper Synthesis report with:
      • summary of what is known (clean)
      • what the dark signal adds
      • what the imagination bridge suggests (if used)
      • overall hypothesis
      • confidence score
      • verdict: YES / NO / MAYBE

  STEP 4 — ROUTING
    YES   → feed_signal() to ProactiveEngine.accumulator as source_type="dark_whisper"
    NO    → log and discard
    MAYBE → park in MongoDB dark_whispers_dormant; reactivate when new evidence arrives

  STEP 5 — DORMANT REACTIVATION
    On every synthesis cycle, dormant MAYBE signals are checked against
    new evidence. If entity/topic overlap >= DARKWEB_REACTIVATION_THRESHOLD,
    the dormant signal is reactivated and re-enters the synthesis queue.

ATTRIBUTION FORMAT (mandatory — crystal clear):
  "DARK WHISPER SYNTHESIS:
   Επαληθευμένα: [A, B, C] (καθαρές πηγές) +
   2 dark whispers (Telegram/pastebin, triage_score=0.61) +
   Creative Nexus link: [concept_X ↔ concept_Y] (ΕΙΚΑΣΙΑ) →
   Hypothesis: [Z]. Confidence: 0.38. ΕΤΥΜΗΓΟΡΙΑ: MAYBE — continuing observation."
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import threading
import time
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Any

from xdart import config

logger = logging.getLogger(__name__)

# ── Synthesis cycle settings ──────────────────────────────────────────────────
_SYNTHESIS_INTERVAL = 600  # run synthesis every 10 minutes (triage runs every 30min)
_MAX_SIGNALS_PER_SYNTHESIS = 20  # cap signals per synthesis cycle
_DORMANT_REACTIVATION_BATCH = 10  # max dormant signals checked per cycle
_OVERLAP_THRESHOLD = 0.20  # minimum entity/topic overlap to consider pairing


# ══════════════════════════════════════════════════════════════════════════════
#  DATA MODELS
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class DarkWhisperSynthesis:
    """The output of one dark whisper synthesis event.

    A synthesis pairs one or more dark signals with related clean patterns
    and produces an intelligence hypothesis with explicit attribution of
    all sources, triage scores, and creative nexus contributions.
    """

    synthesis_id: str
    created_at: str

    # Inputs
    dark_signal_summaries: list[str]       # sanitized_summary from each triaged signal
    dark_signal_channels: list[str]        # channel_name for each signal
    dark_signal_scores: list[float]        # credibility_score for each signal
    clean_pattern_topics: list[str]        # topics from matched clean patterns
    clean_pattern_headlines: list[str]     # representative headlines from clean patterns

    # Creative Nexus (gap-filling imagination — may be empty)
    creative_nexus_used: bool
    creative_link_concept_a: str
    creative_link_concept_b: str
    creative_link_hypothesis: str          # imaginative connection generated by LLM

    # Synthesis output
    hypothesis: str                        # the synthesized intelligence hypothesis
    confidence: float                      # 0-1: overall confidence
    verdict: str                           # "YES" | "NO" | "MAYBE"
    reasoning: str                         # brief analytical justification

    # Full attribution text (formatted for human reading)
    attribution_text: str

    # Routing info
    fed_to_pattern_accumulator: bool = False
    parked_as_dormant: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


# ══════════════════════════════════════════════════════════════════════════════
#  SYNTHESIS SYSTEM PROMPT
# ══════════════════════════════════════════════════════════════════════════════

_SYNTHESIS_SYSTEM_PROMPT = """\
You are Αίολος, a strategic intelligence analyst. You are synthesizing intelligence \
from two layers: (1) verified clean perception data and (2) dark signal intelligence \
that has passed LLM triage but is NOT confirmed.

You must produce a structured synthesis with these MANDATORY properties:
- Dark signals are NEVER presented as confirmed facts. They are leads, possibilities, indicators.
- Creative Nexus contributions are ALWAYS labeled as speculative imagination, not evidence.
- Every component of the synthesis has explicit provenance.
- False flag risk is always acknowledged when > 0.3.
- Confidence reflects the WEAKEST link in the evidence chain.

Output a single valid JSON object with these exact keys:
  "hypothesis": string (1-3 sentences — the synthesized intelligence hypothesis),
  "confidence": float 0-1 (reflect weakest link: dark signals cap at 0.65 regardless of clean data),
  "verdict": string ("YES" if ready for pattern accumulator, "MAYBE" if needs more evidence, "NO" if not worth tracking),
  "reasoning": string (2-3 sentences analytical justification),
  "headline": string (one-line summary for pattern accumulator — if verdict is YES)

Verdict rules:
  YES   = confidence >= 0.40, tactical_relevance_avg >= 0.35, false_flag_risk_avg < 0.55
  NO    = confidence < 0.15 or signals contradict each other completely or purely propaganda
  MAYBE = everything else

Special case — when NO clean pattern corroboration is available (empty CLEAN PATTERNS section):
  If the dark signal has credibility_score >= 0.50 AND tactical_relevance >= 0.40, \
prefer YES over MAYBE even without clean corroboration. \
The signal passed strict LLM triage — that is sufficient evidence on its own.

Do NOT add any text outside the JSON object. Do NOT wrap in markdown."""


def _build_synthesis_user_message(
    dark_signals: list[Any],  # TriagedSignal objects
    clean_topics: set[str],
    clean_headlines: list[str],
    creative_link: dict | None,
) -> str:
    """Build the LLM synthesis prompt."""
    lines = ["SYNTHESIS REQUEST:\n"]

    # Clean evidence
    lines.append(f"CLEAN PATTERNS ({len(clean_headlines)} headlines):")
    for h in clean_headlines[:8]:  # cap at 8 headlines
        lines.append(f"  • {h}")
    lines.append(f"Clean pattern topics: {', '.join(sorted(clean_topics)[:15])}\n")

    # Dark signals
    lines.append(f"DARK SIGNALS ({len(dark_signals)}, already triaged as YES/MAYBE):")
    for i, sig in enumerate(dark_signals, 1):
        lines.append(
            f"  [{i}] Source: {sig.source_type}/{sig.channel_name} | "
            f"triage_cred={sig.credibility_score:.2f} | "
            f"false_flag_risk={sig.false_flag_risk:.2f} | "
            f"attribution={sig.source_attribution}"
        )
        lines.append(f"      Summary: {sig.sanitized_summary or sig.text[:300]}")
    lines.append("")

    # Creative Nexus gap (if used)
    if creative_link:
        lines.append("CREATIVE NEXUS GAP-BRIDGE (SPECULATIVE — not evidence):")
        lines.append(f"  Concept pairing: «{creative_link['concept_a']}» ↔ «{creative_link['concept_b']}»")
        lines.append(f"  Imaginative link: {creative_link.get('curiosity', 'No description generated')}")
        lines.append("  ⚠ This is Creative Nexus imagination — label as SPECULATIVE in all outputs.\n")

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  HELPER: ENTITY/TOPIC OVERLAP
# ══════════════════════════════════════════════════════════════════════════════

def _extract_tokens(text: str) -> set[str]:
    """Extract significant lowercase tokens (>= 4 chars) from text."""
    return {t.lower() for t in re.findall(r'\b\w{4,}\b', text)}


def _overlap_score(text_a: str, topics_b: set[str]) -> float:
    """Jaccard-like overlap between text tokens and a topic set."""
    tokens_a = _extract_tokens(text_a)
    if not tokens_a or not topics_b:
        return 0.0
    topics_b_lower = {t.lower() for t in topics_b}
    intersection = tokens_a & topics_b_lower
    union = tokens_a | topics_b_lower
    return len(intersection) / len(union) if union else 0.0


def _format_attribution(
    dark_signals: list[Any],
    clean_headlines: list[str],
    creative_link: dict | None,
    synthesis_verdict: str,
    synthesis_confidence: float,
    hypothesis: str,
) -> str:
    """Format the mandatory crystal-clear attribution text."""
    n_dark = len(dark_signals)
    dark_sources = ", ".join(
        f"{s.source_type}/{s.channel_name}(cred={s.credibility_score:.2f})"
        for s in dark_signals[:3]  # show first 3
    )
    if n_dark > 3:
        dark_sources += f" +{n_dark - 3} more"

    clean_summary = "; ".join(clean_headlines[:3])
    if len(clean_headlines) > 3:
        clean_summary += f" [+{len(clean_headlines)-3} more]"

    creative_part = ""
    if creative_link:
        creative_part = (
            f"\n   Creative Nexus: «{creative_link['concept_a']}» ↔ «{creative_link['concept_b']}» "
            f"(ΕΙΚΑΣΙΑ/SPECULATIVE)"
        )

    return (
        f"DARK WHISPER SYNTHESIS:\n"
        f"   Επαληθευμένα (verified clean): {clean_summary}\n"
        f"   Dark signals ({n_dark}): {dark_sources}{creative_part}\n"
        f"   → Hypothesis: {hypothesis}\n"
        f"   Confidence: {synthesis_confidence:.2f}. ΕΤΥΜΗΓΟΡΙΑ: {synthesis_verdict}"
    )


# ══════════════════════════════════════════════════════════════════════════════
#  DARK WHISPER ENGINE
# ══════════════════════════════════════════════════════════════════════════════

class DarkWhisperEngine:
    """The synthesis brain of the dark intelligence layer.

    Receives triaged dark signals from DarkSignalTriage, synthesizes them
    with clean patterns from ProactiveEngine, uses Creative Nexus for gaps,
    and routes results appropriately.

    Architecture:
      DarkWebCollector → DirtyPool → DarkSignalTriage → DarkWhisperEngine
                                                              ↕
                                                     ProactiveEngine (clean)
                                                              ↕
                                                      MongoDB + SSE
    """

    DORMANT_COLLECTION = "dark_whispers_dormant"
    SYNTHESIS_COLLECTION = "dark_whisper_syntheses"

    def __init__(
        self,
        llm: Any,
        proactive_engine: Any,
        mongo_store: Any,         # xdart.knowledge.mongo.MongoStore
        mongo_db: Any,            # raw pymongo db handle
        dirty_pool: "DirtyPool",
        triage: "DarkSignalTriage",
        collector: "DarkWebCollector",
    ) -> None:
        self.llm = llm
        self.proactive = proactive_engine
        self.mongo_store = mongo_store   # for Creative Nexus calls
        self.db = mongo_db              # for direct collection access
        self.pool = dirty_pool
        self.triage = triage
        self.collector = collector

        self._running = False
        self._thread: threading.Thread | None = None
        self._total_syntheses = 0
        self._total_yes_fed = 0
        self._total_maybe_dormant = 0
        self._last_synthesis_at: str = ""

        # Ensure MongoDB indexes
        if self.db is not None:
            try:
                self.db[self.DORMANT_COLLECTION].create_index(
                    [("content_hash", 1)], background=True
                )
                self.db[self.DORMANT_COLLECTION].create_index(
                    [("parked_at", -1)], background=True
                )
                self.db[self.SYNTHESIS_COLLECTION].create_index(
                    [("created_at", -1)], background=True
                )
            except Exception as exc:
                logger.debug("[DarkWhisper] Index creation failed: %s", exc)

    def start(self) -> None:
        """Start the synthesis background thread."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(
            target=self._loop,
            name="dark-whisper-synthesis",
            daemon=True,
        )
        self._thread.start()
        logger.info(
            "[DarkWhisper] Synthesis engine started — interval=%ds", _SYNTHESIS_INTERVAL
        )

    def stop(self) -> None:
        """Stop the synthesis engine."""
        self._running = False
        logger.info("[DarkWhisper] Synthesis engine stopped")

    def stats(self) -> dict:
        return {
            "running": self._running,
            "total_syntheses": self._total_syntheses,
            "yes_fed_to_accumulator": self._total_yes_fed,
            "maybe_parked_dormant": self._total_maybe_dormant,
            "last_synthesis_at": self._last_synthesis_at,
            "triage": self.triage.stats(),
            "collector": self.collector.stats(),
        }

    def get_recent_syntheses(self, limit: int = 10) -> list[dict]:
        """Return recent synthesis reports from MongoDB."""
        if self.db is None:
            return []
        try:
            return list(
                self.db[self.SYNTHESIS_COLLECTION]
                .find({}, {"_id": 0})
                .sort("created_at", -1)
                .limit(limit)
            )
        except Exception:
            return []

    def get_dormant_signals(self, limit: int = 20) -> list[dict]:
        """Return dormant MAYBE signals from MongoDB."""
        if self.db is None:
            return []
        try:
            return list(
                self.db[self.DORMANT_COLLECTION]
                .find({}, {"_id": 0})
                .sort("parked_at", -1)
                .limit(limit)
            )
        except Exception:
            return []

    # ── Main loop ─────────────────────────────────────────────────────────────

    def _loop(self) -> None:
        """Synthesis background loop (runs in dedicated thread)."""
        # Startup delay
        time.sleep(120)
        while self._running:
            try:
                self._synthesis_cycle()
            except Exception as exc:
                logger.warning("[DarkWhisper] Synthesis cycle error: %s", exc)
            time.sleep(_SYNTHESIS_INTERVAL)

    def _synthesis_cycle(self) -> None:
        """One full synthesis cycle."""
        # Step 1: Run triage on any untriaged signals in dirty pool
        triaged = self.triage.run_triage_batch()
        yes_signals = [s for s in triaged if s.is_yes]
        maybe_signals = [s for s in triaged if s.is_maybe]

        # Also check dormant signals for reactivation
        reactivated = self._check_dormant_reactivation()
        yes_signals.extend([s for s in reactivated if s.is_yes])
        maybe_signals.extend([s for s in reactivated if s.is_maybe])

        actionable = yes_signals + maybe_signals
        if not actionable:
            logger.debug("[DarkWhisper] No actionable signals this cycle")
            return

        # Step 2: Get current active clean patterns from ProactiveEngine
        clean_patterns = self._get_clean_patterns()

        # Step 3: Synthesize
        for signal in actionable[:_MAX_SIGNALS_PER_SYNTHESIS]:
            try:
                self._synthesize_single(signal, clean_patterns)
            except Exception as exc:
                logger.warning("[DarkWhisper] Synthesis error for signal: %s", exc)

    def _get_clean_patterns(self) -> list[Any]:
        """Get active EmergentPattern objects from ProactiveEngine."""
        try:
            if hasattr(self.proactive, "accumulator"):
                return list(self.proactive.accumulator._patterns)
        except Exception:
            pass
        return []

    def _synthesize_single(self, signal: Any, clean_patterns: list[Any]) -> None:
        """Synthesize one triaged dark signal with the best matching clean patterns."""

        # Find clean patterns with entity/topic overlap
        matched_patterns = []
        signal_text = f"{signal.sanitized_summary or signal.text}"
        for pat in clean_patterns:
            pat_topics = pat.topics if hasattr(pat, "topics") else set()
            score = _overlap_score(signal_text, pat_topics)
            if score >= _OVERLAP_THRESHOLD:
                matched_patterns.append((score, pat))
        matched_patterns.sort(key=lambda x: x[0], reverse=True)
        top_patterns = [p for _, p in matched_patterns[:3]]

        # Extract clean evidence from matched patterns
        clean_topics: set[str] = set()
        clean_headlines: list[str] = []
        for pat in top_patterns:
            clean_topics |= (pat.topics if hasattr(pat, "topics") else set())
            for sig in list(pat.signals)[-5:]:  # last 5 signals from each pattern
                clean_headlines.append(sig.headline)

        # Step 3: Gap detection + Creative Nexus
        creative_link: dict | None = None
        has_gap = len(top_patterns) == 0 or (
            len(top_patterns) > 0 and matched_patterns[0][0] < 0.35
        )

        if has_gap and self.mongo_store is not None:
            creative_link = self._invoke_creative_nexus(signal, clean_topics)

        # Step 4: LLM Synthesis
        user_msg = _build_synthesis_user_message(
            [signal], clean_topics, clean_headlines, creative_link
        )

        try:
            raw_response = self.llm.call(
                system_prompt=_SYNTHESIS_SYSTEM_PROMPT,
                user_prompt=user_msg,
                max_tokens=1024,
                temperature=0.25,
                thinking=False,
            )
        except Exception as exc:
            logger.warning("[DarkWhisper] LLM synthesis call failed: %s", exc)
            return

        # Parse LLM response
        try:
            raw_response = raw_response.strip()
            if raw_response.startswith("```"):
                raw_response = re.sub(r"^```[a-z]*\n?", "", raw_response)
                raw_response = re.sub(r"\n?```$", "", raw_response)
                raw_response = raw_response.strip()
            result = json.loads(raw_response)
        except Exception:
            logger.warning("[DarkWhisper] Failed to parse synthesis JSON")
            return

        verdict = result.get("verdict", "NO").upper().strip()
        if verdict not in ("YES", "NO", "MAYBE"):
            verdict = "MAYBE"

        confidence = max(0.0, min(1.0, float(result.get("confidence", 0.2))))
        hypothesis = result.get("hypothesis", "No hypothesis generated")
        reasoning = result.get("reasoning", "")
        headline = result.get("headline", hypothesis[:120])

        # Format attribution text
        attribution = _format_attribution(
            [signal], clean_headlines, creative_link,
            verdict, confidence, hypothesis,
        )

        # Build synthesis object
        now = datetime.now(timezone.utc).isoformat()
        synthesis_id = f"dw_{int(time.time() * 1000)}"

        synthesis = DarkWhisperSynthesis(
            synthesis_id=synthesis_id,
            created_at=now,
            dark_signal_summaries=[signal.sanitized_summary or signal.text[:200]],
            dark_signal_channels=[signal.channel_name],
            dark_signal_scores=[signal.credibility_score],
            clean_pattern_topics=list(clean_topics)[:20],
            clean_pattern_headlines=clean_headlines[:8],
            creative_nexus_used=creative_link is not None,
            creative_link_concept_a=creative_link.get("concept_a", "") if creative_link else "",
            creative_link_concept_b=creative_link.get("concept_b", "") if creative_link else "",
            creative_link_hypothesis=creative_link.get("curiosity", "") if creative_link else "",
            hypothesis=hypothesis,
            confidence=confidence,
            verdict=verdict,
            reasoning=reasoning,
            attribution_text=attribution,
        )

        # Update credibility chain on the signal
        if hasattr(signal, "credibility_chain") and isinstance(signal.credibility_chain, dict):
            signal.credibility_chain["synthesis"] = {
                "synthesis_id": synthesis_id,
                "verdict": verdict,
                "confidence": confidence,
                "creative_nexus_used": creative_link is not None,
                "synthesized_at": now,
            }

        # Step 5: Route
        if verdict == "YES":
            self._route_yes(signal, synthesis, headline)
        elif verdict == "MAYBE":
            self._route_maybe(signal, synthesis)
        else:
            logger.info("[DarkWhisper] NO synthesis for: %.60s (conf=%.2f)", hypothesis, confidence)

        # Persist synthesis to MongoDB regardless of verdict
        self._persist_synthesis(synthesis)
        self._total_syntheses += 1
        self._last_synthesis_at = now

        logger.info(
            "[DarkWhisper] Synthesis %s — verdict=%s, conf=%.2f, creative_nexus=%s",
            synthesis_id, verdict, confidence, creative_link is not None,
        )

    def _invoke_creative_nexus(
        self,
        signal: Any,
        clean_topics: set[str],
    ) -> dict | None:
        """Use the Creative Nexus to bridge a gap between a dark signal and clean concepts.

        Instead of random pairing (run_imagination_cycle), we extract the most
        distinctive concept from the dark signal and pair it with the closest
        clean concept. The LLM generates the imaginative link.

        The link is stored in MongoDB creative_links with tag 'dark_whisper_gap'
        so Αίολος knows this link was born from dark signal analysis.
        """
        try:
            # Extract the most meaningful concept from the dark signal.
            # Priority order:
            #   1. triage-identified entities (most precise — already extracted by LLM)
            #   2. triage-identified topics
            #   3. fallback: distinctive token from signal text
            concept_dark = ""

            # 1. Use triage entities if available on the signal
            entities = getattr(signal, "entities", []) or []
            if entities:
                concept_dark = entities[0]

            # 2. Use triage topics if no entities
            if not concept_dark:
                topics = getattr(signal, "topics", []) or []
                if topics:
                    concept_dark = topics[0]

            # 3. Fallback: extract distinctive token from signal text
            if not concept_dark:
                signal_text = signal.sanitized_summary or signal.text
                signal_tokens = [
                    t.lower() for t in re.findall(r'\b[A-Za-z\u0370-\u03FF]{4,}\b', signal_text)
                    if len(t) >= 4
                ]
                if not signal_tokens:
                    return None
                _STOPWORDS = {
                    # Basic function words
                    "that", "this", "with", "from", "have", "will", "been",
                    "were", "they", "their", "said", "also", "more", "than",
                    "when", "what", "where", "which", "into", "over", "after",
                    # News filler
                    "report", "reports", "news", "update", "updates", "according",
                    "sources", "official", "officials", "government", "minister",
                    "president", "says", "told", "added", "noted", "statement",
                    "latest", "breaking", "developing", "amid", "despite",
                    # Generic English
                    "through", "under", "before", "during", "since", "near",
                    "across", "against", "between", "within", "free", "open",
                    "close", "second", "third", "major", "inside", "outside",
                    "must", "former", "annual", "modern", "list", "request",
                    "data", "system", "systems", "company", "center", "department",
                    "operation", "phase", "base", "business", "financial",
                    # Calendar / year noise
                    "2024", "2025", "2026", "2027", "2028",
                    # High-frequency political noise (always in news; no signal)
                    "trump", "biden", "obama", "putin", "modi", "macron",
                    "china", "russia", "iran", "israel", "ukraine", "europe",
                    "america", "american", "chinese", "russian", "european",
                    # Financial generic
                    "bank", "banks", "banking", "market", "markets", "sector",
                    "economy", "economic", "trade", "fund", "funds", "stock",
                    "price", "prices", "rate", "rates", "growth", "spending",
                    "budget", "revenue", "billion", "million", "trillion",
                    "deal", "deals", "agreement", "agreements",
                    # Meta-action verbs
                    "record", "write", "read", "plan", "plans", "announce",
                    "launch", "sign", "adopt", "vote", "publish", "release",
                }
                significant = [t for t in signal_tokens if t not in _STOPWORDS]
                concept_dark = significant[0] if significant else signal_tokens[0]

            # Pick the most specific clean concept (prefer longer, more informative ones)
            clean_concepts = sorted(clean_topics, key=len, reverse=True)[:10]
            # Filter clean concept list against the same stop-word set to avoid bridging
            # with generic terms like "bank" or "record" that carry no gap signal.
            _CONCEPT_STOPWORDS = {
                "bank", "banks", "banking", "market", "markets", "sector", "economy",
                "economic", "trade", "fund", "funds", "stock", "price", "prices",
                "rate", "rates", "growth", "deal", "deals", "agreement", "agreements",
                "trump", "biden", "putin", "china", "russia", "iran", "israel",
                "ukraine", "europe", "america", "american", "chinese", "russian",
                "european", "record", "write", "plan", "announce", "launch",
                "data", "system", "company", "government", "minister", "president",
            }
            clean_concepts = [c for c in clean_concepts if c.lower() not in _CONCEPT_STOPWORDS]
            concept_clean = clean_concepts[0] if clean_concepts else "geopolitical_risk"

            # Also skip bridging if concept_dark itself is a stop-word
            if concept_dark.lower() in _CONCEPT_STOPWORDS:
                logger.debug(
                    "[DarkWhisper/CreativeNexus] Skipping bridge — dark concept '%s' is a stop-word",
                    concept_dark,
                )
                return None

            # Generate the imaginative connection via LLM
            curiosity = ""
            try:
                prompt = (
                    "You are a creative intelligence analyst examining a dark signal. "
                    "You have identified a possible connection gap between a dark threat concept "
                    "and a clean geopolitical/economic concept. "
                    "Generate ONE thought-provoking speculative hypothesis — a 1-2 sentence bridge — "
                    "connecting these two concepts. Be analytical, not sensational. "
                    "This will be LABELED as speculative in all reports. Answer in Greek."
                )
                user_msg = f"Dark concept: \"{concept_dark}\"\nClean concept: \"{concept_clean}\""
                curiosity = self.llm.call(
                    system_prompt=prompt,
                    user_prompt=user_msg,
                    max_tokens=200,
                    temperature=0.85,
                    thinking=False,
                )
                curiosity = (curiosity or "").strip()
            except Exception as exc:
                logger.debug("[DarkWhisper/CreativeNexus] LLM imagination failed: %s", exc)

            # Store in MongoDB creative_links (with dark_whisper_gap tag)
            if self.mongo_store is not None:
                try:
                    self.mongo_store.create_creative_link(
                        concept_a=concept_dark,
                        concept_b=concept_clean,
                        context=f"Dark whisper gap-bridge: {signal.source_type}/{signal.channel_name}",
                        strength=0.15,
                        tags=["dark_whisper_gap"],
                        triggered_curiosity=curiosity,
                    )
                except Exception as exc:
                    logger.debug("[DarkWhisper/CreativeNexus] create_creative_link failed: %s", exc)

            link = {
                "concept_a": concept_dark,
                "concept_b": concept_clean,
                "curiosity": curiosity,
                "source": "dark_whisper_gap",
            }
            logger.info(
                "[DarkWhisper/CreativeNexus] Gap bridge: «%s» ↔ «%s»",
                concept_dark, concept_clean,
            )
            return link

        except Exception as exc:
            logger.warning("[DarkWhisper/CreativeNexus] Error: %s", exc)
            return None

    def _route_yes(
        self,
        signal: Any,
        synthesis: DarkWhisperSynthesis,
        headline: str,
    ) -> None:
        """Route a YES synthesis directly to ProactiveEngine evaluation.

        Dark whisper syntheses are ALREADY LLM-synthesised intelligence products.
        They bypass PatternAccumulator (which requires 5+ clustered signals) and
        go straight to evaluate_and_notify() so they reach the user immediately.
        The old feed_signal() path was silently swallowing all dark content because
        each synthesis is a unique topic — they never accumulated to 5+.
        """
        try:
            event_data = {
                "headlines": [f"[DARK WHISPER] {headline}"],
                "synthesis_id": synthesis.synthesis_id,
                "confidence": synthesis.confidence,
                "attribution": synthesis.attribution_text,
                "dark_channels": synthesis.dark_signal_channels,
                "dark_scores": synthesis.dark_signal_scores,
                "creative_nexus_used": synthesis.creative_nexus_used,
                "source_types": ["dark_whisper"],
                "domains": [],  # classified from headline by evaluate_and_notify
                "verdict": "YES",
            }
            context_text = (
                f"DARK WHISPER SYNTHESIS (confidence={synthesis.confidence:.2f}):\n"
                f"{synthesis.attribution_text}\n\n"
                f"Dark signal channels: {', '.join(synthesis.dark_signal_channels)}\n"
                f"Clean pattern topics used: {', '.join(synthesis.clean_pattern_topics[:10])}"
            )
            # Submit to ProactiveEngine's dedicated evaluation pool so this
            # never blocks the DarkWhisper synthesis thread.
            self.proactive._eval_pool.submit(
                self.proactive.evaluate_and_notify,
                "dark_whisper_synthesis",
                event_data,
                context_text,
            )
            synthesis.fed_to_pattern_accumulator = True
            self._total_yes_fed += 1
            logger.info(
                "[DarkWhisper] YES → evaluate_and_notify (direct): %s (conf=%.2f)",
                headline[:80], synthesis.confidence,
            )
        except Exception as exc:
            logger.warning("[DarkWhisper] _route_yes failed: %s", exc)

    def _route_maybe(
        self,
        signal: Any,
        synthesis: DarkWhisperSynthesis,
    ) -> None:
        """Park a MAYBE synthesis in dormant memory for future reactivation."""
        if self.db is None:
            return
        try:
            dormant_doc = {
                "synthesis_id": synthesis.synthesis_id,
                "content_hash": signal.content_hash,
                "text": signal.text[:500],
                "sanitized_summary": signal.sanitized_summary,
                "channel_name": signal.channel_name,
                "source_type": signal.source_type,
                "credibility_score": signal.credibility_score,
                "false_flag_risk": signal.false_flag_risk,
                "source_attribution": signal.source_attribution,
                "clean_topics": synthesis.clean_pattern_topics,
                "hypothesis": synthesis.hypothesis,
                "confidence": synthesis.confidence,
                "creative_nexus_used": synthesis.creative_nexus_used,
                "creative_link_concept_a": synthesis.creative_link_concept_a,
                "creative_link_concept_b": synthesis.creative_link_concept_b,
                "attribution_text": synthesis.attribution_text,
                "parked_at": synthesis.created_at,
                "reactivation_count": 0,
                "reactivated": False,
                "verdict_history": [{"verdict": "MAYBE", "at": synthesis.created_at}],
            }
            # Use content_hash as idempotency key
            self.db[self.DORMANT_COLLECTION].update_one(
                {"content_hash": signal.content_hash},
                {"$set": dormant_doc},
                upsert=True,
            )
            synthesis.parked_as_dormant = True
            self._total_maybe_dormant += 1
            logger.info(
                "[DarkWhisper] MAYBE → dormant memory: %.60s (conf=%.2f)",
                synthesis.hypothesis, synthesis.confidence,
            )
        except Exception as exc:
            logger.warning("[DarkWhisper] park_dormant failed: %s", exc)

    def _check_dormant_reactivation(self) -> list[Any]:
        """Check dormant MAYBE signals against current active clean patterns.

        A dormant signal is reactivated if its stored topics overlap with
        current active pattern topics by >= DARKWEB_REACTIVATION_THRESHOLD.

        Returns list of TriagedSignal-compatible objects for re-synthesis.
        """
        if self.db is None:
            return []

        try:
            dormant_docs = list(
                self.db[self.DORMANT_COLLECTION]
                .find({"reactivated": False})
                .sort("parked_at", 1)
                .limit(_DORMANT_REACTIVATION_BATCH)
            )
        except Exception:
            return []

        if not dormant_docs:
            return []

        # Get current clean topics
        current_topics: set[str] = set()
        for pat in self._get_clean_patterns():
            if hasattr(pat, "topics"):
                current_topics |= pat.topics

        if not current_topics:
            return []

        reactivated = []
        for doc in dormant_docs:
            stored_topics = set(doc.get("clean_topics", []))
            if not stored_topics:
                continue

            # Overlap check
            overlap = len(stored_topics & current_topics) / max(len(stored_topics), 1)
            if overlap < config.DARKWEB_REACTIVATION_THRESHOLD:
                continue

            logger.info(
                "[DarkWhisper] Reactivating dormant signal (overlap=%.2f): %.60s",
                overlap, doc.get("hypothesis", "?"),
            )

            # Mark as reactivated
            try:
                self.db[self.DORMANT_COLLECTION].update_one(
                    {"_id": doc["_id"]},
                    {
                        "$set": {"reactivated": True, "reactivated_at": datetime.now(timezone.utc).isoformat()},
                        "$inc": {"reactivation_count": 1},
                        "$push": {"verdict_history": {
                            "verdict": "REACTIVATED",
                            "at": datetime.now(timezone.utc).isoformat(),
                            "overlap": overlap,
                        }},
                    },
                )
            except Exception:
                pass

            # Create a minimal TriagedSignal-like object for re-synthesis
            reactivated.append(_DormantReactivated(doc))

        return reactivated

    def trigger_resonance_check(
        self,
        pattern_topics: set[str],
        pattern_entities: set[str],
        pattern_headlines: list[str],
    ) -> None:
        """Called by PatternAccumulator immediately when a pattern fires.

        Rather than waiting for the next scheduled synthesis cycle (up to 10 min),
        this immediately checks dormant dark whispers against the freshly fired
        pattern's topics and entities. If overlap >= DARKWEB_REACTIVATION_THRESHOLD,
        synthesis is triggered right now.

        This is the core of Problem B: every pattern creation/firing event
        is also a potential dark signal reactivation event. The two layers
        are now permanently coupled.

        Non-blocking: work runs in a daemon thread.
        """
        if self.db is None:
            return

        def _check() -> None:
            try:
                dormant_docs = list(
                    self.db[self.DORMANT_COLLECTION]
                    .find({"reactivated": False})
                    .sort("parked_at", 1)
                    .limit(_DORMANT_REACTIVATION_BATCH)
                )
                if not dormant_docs:
                    return

                triggered = []
                for doc in dormant_docs:
                    summary = doc.get("sanitized_summary", "") or doc.get("text", "")
                    # Topic overlap + entity boost
                    score = _overlap_score(summary, pattern_topics)
                    score += _overlap_score(summary, pattern_entities) * 0.5
                    if score >= config.DARKWEB_REACTIVATION_THRESHOLD:
                        triggered.append((score, doc))

                if not triggered:
                    logger.debug(
                        "[DarkWhisper] Resonance check: no dormant signal matches "
                        "topics %s", sorted(pattern_topics)[:5],
                    )
                    return

                triggered.sort(key=lambda x: x[0], reverse=True)
                logger.info(
                    "[DarkWhisper] Pattern resonance: %d dormant signal(s) match "
                    "fired pattern (topics=%s)",
                    len(triggered), sorted(pattern_topics)[:6],
                )

                # Build a minimal stub so _synthesize_single() can extract
                # clean topics and headlines — same interface as EmergentPattern
                class _PatternStub:
                    def __init__(
                        self,
                        topics: set[str],
                        headlines: list[str],
                    ) -> None:
                        self.topics = set(topics)
                        self.signals = [
                            type("_S", (), {"headline": h, "timestamp": 0.0})()
                            for h in headlines
                        ]

                stub = _PatternStub(pattern_topics, pattern_headlines)

                for _, doc in triggered[:3]:  # max 3 re-syntheses per pattern fire
                    try:
                        wrapper = _DormantReactivated(doc)
                        self._synthesize_single(wrapper, [stub])
                        # Mark reactivated so it doesn't fire again on next cycle
                        self.db[self.DORMANT_COLLECTION].update_one(
                            {"_id": doc["_id"]},
                            {
                                "$set": {
                                    "reactivated": True,
                                    "reactivated_at": datetime.now(timezone.utc).isoformat(),
                                    "reactivation_trigger": "pattern_fire",
                                },
                                "$inc": {"reactivation_count": 1},
                                "$push": {"verdict_history": {
                                    "verdict": "REACTIVATED_BY_PATTERN",
                                    "at": datetime.now(timezone.utc).isoformat(),
                                    "pattern_topics": sorted(pattern_topics)[:8],
                                }},
                            },
                        )
                    except Exception as exc:
                        logger.debug(
                            "[DarkWhisper] Resonance synthesis for dormant doc failed: %s", exc
                        )

            except Exception as exc:
                logger.debug("[DarkWhisper] trigger_resonance_check failed: %s", exc)

        threading.Thread(target=_check, daemon=True, name="darkwhisper-resonance").start()

    def _persist_synthesis(self, synthesis: DarkWhisperSynthesis) -> None:
        """Store synthesis report in MongoDB."""
        if self.db is None:
            return
        try:
            self.db[self.SYNTHESIS_COLLECTION].insert_one(synthesis.to_dict())
        except Exception as exc:
            logger.debug("[DarkWhisper] persist_synthesis failed: %s", exc)


# ── Helper: wrap a dormant doc as a TriagedSignal-compatible object ───────────

class _DormantReactivated:
    """Minimal wrapper around a dormant MongoDB document for re-synthesis."""

    def __init__(self, doc: dict) -> None:
        self.text = doc.get("text", "")
        self.source_url = ""
        self.source_type = doc.get("source_type", "dormant")
        self.channel_name = doc.get("channel_name", "dormant")
        self.collected_at = doc.get("parked_at", "")
        self.published_at = doc.get("parked_at", "")
        self.raw_credibility = doc.get("credibility_score", 0.2)
        self.appeared_in_n_channels = 1
        self.content_hash = doc.get("content_hash", "")
        self.triaged_at = doc.get("parked_at", "")
        self.credibility_score = doc.get("credibility_score", 0.2)
        self.false_flag_risk = doc.get("false_flag_risk", 0.5)
        self.source_attribution = doc.get("source_attribution", "unknown")
        self.language_origin = ""
        self.tactical_relevance = 0.3
        self.verdict = "MAYBE"
        self.rejection_reason = ""
        self.sanitized_summary = doc.get("sanitized_summary", "")
        self.credibility_chain = {}
        self.is_yes = False
        self.is_maybe = True
        self.is_no = False
