"""
XDART-Φ × XHEART — Infrastructure Cascade Model

Ported from WorldMonitor infrastructure-cascade logic.

Models how disruptions propagate through interconnected global infrastructure.
Dependency graph links undersea cables, pipelines, ports, chokepoints, and
countries with weighted edges representing capacity dependencies.

Cascade propagation: BFS, depth ≤ 3
Impact: strength = edge_weight × disruption_level × (1 - redundancy)

Strategic chokepoints:
  - Strait of Hormuz: 80% Japan oil, 70% SK oil, 60% India oil, 40% China oil
  - Suez Canal: EU-Asia trade (Germany, Italy, UK, China)
  - Malacca Strait: 80% China oil transit
  - Bab el-Mandeb: Red Sea trade route to Suez
  - Turkish Straits: Black Sea → Mediterranean
  - Panama Canal: Americas east-west trade
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum

logger = logging.getLogger("xdart.perception.infrastructure")


# ─────────────────────────────────────────────────────────────────────
# Node Types
# ─────────────────────────────────────────────────────────────────────

class NodeType(str, Enum):
    CHOKEPOINT = "chokepoint"
    PORT = "port"
    PIPELINE = "pipeline"
    CABLE = "cable"
    COUNTRY = "country"


@dataclass
class InfraNode:
    """A node in the infrastructure dependency graph."""
    id: str
    name: str
    node_type: NodeType
    region: str = ""
    weight: float = 1.0          # node importance (0-1)
    redundancy: float = 0.0      # 0 = no redundancy, 1 = fully redundant


@dataclass
class InfraEdge:
    """Directed dependency edge between infrastructure nodes."""
    source_id: str
    target_id: str
    weight: float                # dependency strength (0-1)
    dependency_type: str = ""    # "oil", "trade", "data", "energy"


@dataclass
class CascadeAlert:
    """Alert generated by infrastructure cascade simulation."""
    trigger_node: str
    affected_nodes: list[str]
    max_depth: int
    total_impact: float
    summary: str
    affected_countries: list[str]


# ─────────────────────────────────────────────────────────────────────
# Infrastructure Graph (curated strategic nodes + edges)
# ─────────────────────────────────────────────────────────────────────

# Strategic chokepoints
CHOKEPOINTS: dict[str, InfraNode] = {
    "hormuz": InfraNode("hormuz", "Strait of Hormuz", NodeType.CHOKEPOINT, "ME", 0.95, 0.05),
    "suez": InfraNode("suez", "Suez Canal", NodeType.CHOKEPOINT, "ME", 0.90, 0.15),
    "malacca": InfraNode("malacca", "Strait of Malacca", NodeType.CHOKEPOINT, "ASIA", 0.90, 0.10),
    "bab_el_mandeb": InfraNode("bab_el_mandeb", "Bab el-Mandeb Strait", NodeType.CHOKEPOINT, "ME", 0.85, 0.10),
    "turkish_straits": InfraNode("turkish_straits", "Turkish Straits (Bosphorus/Dardanelles)", NodeType.CHOKEPOINT, "EU", 0.80, 0.20),
    "panama": InfraNode("panama", "Panama Canal", NodeType.CHOKEPOINT, "LATAM", 0.80, 0.25),
    "gibraltar": InfraNode("gibraltar", "Strait of Gibraltar", NodeType.CHOKEPOINT, "EU", 0.70, 0.30),
    "cape_good_hope": InfraNode("cape_good_hope", "Cape of Good Hope", NodeType.CHOKEPOINT, "AF", 0.60, 0.50),
    "lombok": InfraNode("lombok", "Lombok Strait", NodeType.CHOKEPOINT, "ASIA", 0.50, 0.40),
}

# Major strategic ports (weighted by type: oil/LNG=0.9, container=0.7, naval=0.4)
PORTS: dict[str, InfraNode] = {
    "ras_tanura": InfraNode("ras_tanura", "Ras Tanura (Saudi)", NodeType.PORT, "ME", 0.9, 0.10),
    "kharg_island": InfraNode("kharg_island", "Kharg Island (Iran)", NodeType.PORT, "ME", 0.9, 0.05),
    "fujairah": InfraNode("fujairah", "Fujairah (UAE)", NodeType.PORT, "ME", 0.9, 0.15),
    "shanghai": InfraNode("shanghai", "Port of Shanghai", NodeType.PORT, "CN", 0.7, 0.30),
    "singapore": InfraNode("singapore", "Port of Singapore", NodeType.PORT, "ASIA", 0.7, 0.25),
    "rotterdam": InfraNode("rotterdam", "Port of Rotterdam", NodeType.PORT, "EU", 0.7, 0.30),
    "jebel_ali": InfraNode("jebel_ali", "Jebel Ali (Dubai)", NodeType.PORT, "ME", 0.7, 0.25),
    "busan": InfraNode("busan", "Busan (South Korea)", NodeType.PORT, "ASIA", 0.7, 0.25),
    "norfolk": InfraNode("norfolk", "Norfolk Naval Station (US)", NodeType.PORT, "US", 0.4, 0.40),
    "yokosuka": InfraNode("yokosuka", "Yokosuka Naval Base (Japan)", NodeType.PORT, "JP", 0.4, 0.35),
    "tartus": InfraNode("tartus", "Tartus Naval Base (Syria/Russia)", NodeType.PORT, "ME", 0.4, 0.20),
}

# Major pipelines
PIPELINES: dict[str, InfraNode] = {
    "nord_stream": InfraNode("nord_stream", "Nord Stream Pipeline", NodeType.PIPELINE, "EU", 0.85, 0.30),
    "turkstream": InfraNode("turkstream", "TurkStream Pipeline", NodeType.PIPELINE, "EU", 0.75, 0.40),
    "east_med": InfraNode("east_med", "East Mediterranean Pipeline", NodeType.PIPELINE, "ME", 0.60, 0.50),
    "druzhba": InfraNode("druzhba", "Druzhba Pipeline (Friendship)", NodeType.PIPELINE, "EU", 0.80, 0.25),
    "btc": InfraNode("btc", "BTC Pipeline (Baku-Tbilisi-Ceyhan)", NodeType.PIPELINE, "ME", 0.75, 0.30),
    "tapi": InfraNode("tapi", "TAPI Pipeline", NodeType.PIPELINE, "ASIA", 0.60, 0.50),
    "keystone_xl": InfraNode("keystone_xl", "Keystone Pipeline System", NodeType.PIPELINE, "US", 0.70, 0.35),
}

# Major undersea cables
CABLES: dict[str, InfraNode] = {
    "sea_me_we_6": InfraNode("sea_me_we_6", "SEA-ME-WE 6 (Asia-Middle East-Western Europe)", NodeType.CABLE, "MULTI", 0.85, 0.25),
    "aae1": InfraNode("aae1", "AAE-1 (Asia-Africa-Europe 1)", NodeType.CABLE, "MULTI", 0.80, 0.30),
    "peace": InfraNode("peace", "PEACE Cable (Pakistan-East Africa-Connecting Europe)", NodeType.CABLE, "MULTI", 0.75, 0.35),
    "marea": InfraNode("marea", "MAREA (US-Spain)", NodeType.CABLE, "US-EU", 0.80, 0.30),
    "dunant": InfraNode("dunant", "Dunant (US-France, Google)", NodeType.CABLE, "US-EU", 0.80, 0.30),
    "equiano": InfraNode("equiano", "Equiano (Portugal-South Africa, Google)", NodeType.CABLE, "EU-AF", 0.70, 0.35),
    "2africa": InfraNode("2africa", "2Africa (Meta, circumnavigates Africa)", NodeType.CABLE, "MULTI", 0.85, 0.25),
}

# Country nodes (for cascade endpoints)
COUNTRY_NODES: dict[str, InfraNode] = {
    "JP": InfraNode("JP", "Japan", NodeType.COUNTRY, "ASIA", 0.9, 0.30),
    "KR": InfraNode("KR", "South Korea", NodeType.COUNTRY, "ASIA", 0.85, 0.25),
    "CN": InfraNode("CN", "China", NodeType.COUNTRY, "ASIA", 0.95, 0.20),
    "IN": InfraNode("IN", "India", NodeType.COUNTRY, "ASIA", 0.85, 0.25),
    "DE": InfraNode("DE", "Germany", NodeType.COUNTRY, "EU", 0.90, 0.30),
    "IT": InfraNode("IT", "Italy", NodeType.COUNTRY, "EU", 0.80, 0.30),
    "GB": InfraNode("GB", "United Kingdom", NodeType.COUNTRY, "EU", 0.90, 0.30),
    "US": InfraNode("US", "United States", NodeType.COUNTRY, "US", 0.95, 0.40),
    "SA": InfraNode("SA", "Saudi Arabia", NodeType.COUNTRY, "ME", 0.85, 0.15),
    "TR": InfraNode("TR", "Turkey", NodeType.COUNTRY, "ME-EU", 0.80, 0.25),
    "EG": InfraNode("EG", "Egypt", NodeType.COUNTRY, "ME-AF", 0.75, 0.20),
    "SG": InfraNode("SG", "Singapore", NodeType.COUNTRY, "ASIA", 0.80, 0.30),
}

# ─────────────────────────────────────────────────────────────────────
# Dependency Edges
# ─────────────────────────────────────────────────────────────────────

EDGES: list[InfraEdge] = [
    # Strait of Hormuz dependencies
    InfraEdge("hormuz", "JP", 0.80, "oil"),       # 80% Japan oil
    InfraEdge("hormuz", "KR", 0.70, "oil"),        # 70% South Korea oil
    InfraEdge("hormuz", "IN", 0.60, "oil"),        # 60% India oil
    InfraEdge("hormuz", "CN", 0.40, "oil"),        # 40% China oil
    InfraEdge("hormuz", "ras_tanura", 0.90, "oil"),
    InfraEdge("hormuz", "kharg_island", 0.95, "oil"),
    InfraEdge("hormuz", "fujairah", 0.70, "oil"),

    # Suez Canal dependencies
    InfraEdge("suez", "DE", 0.65, "trade"),
    InfraEdge("suez", "IT", 0.70, "trade"),
    InfraEdge("suez", "GB", 0.55, "trade"),
    InfraEdge("suez", "CN", 0.45, "trade"),
    InfraEdge("suez", "EG", 0.90, "revenue"),     # Egypt's main revenue source

    # Malacca Strait dependencies
    InfraEdge("malacca", "CN", 0.80, "oil"),       # 80% China oil transit
    InfraEdge("malacca", "JP", 0.60, "trade"),
    InfraEdge("malacca", "KR", 0.55, "trade"),
    InfraEdge("malacca", "SG", 0.90, "trade"),
    InfraEdge("malacca", "singapore", 0.95, "port"),

    # Bab el-Mandeb → Suez connection
    InfraEdge("bab_el_mandeb", "suez", 0.85, "trade"),

    # Turkish Straits
    InfraEdge("turkish_straits", "TR", 0.80, "trade"),
    InfraEdge("turkish_straits", "DE", 0.30, "energy"),

    # Pipeline → Country dependencies
    InfraEdge("nord_stream", "DE", 0.75, "energy"),
    InfraEdge("turkstream", "TR", 0.60, "energy"),
    InfraEdge("druzhba", "DE", 0.40, "energy"),
    InfraEdge("btc", "TR", 0.50, "energy"),

    # Cable → Country dependencies
    InfraEdge("sea_me_we_6", "IN", 0.65, "data"),
    InfraEdge("sea_me_we_6", "SG", 0.55, "data"),
    InfraEdge("sea_me_we_6", "DE", 0.40, "data"),
    InfraEdge("marea", "US", 0.50, "data"),
    InfraEdge("marea", "DE", 0.30, "data"),
    InfraEdge("2africa", "EG", 0.45, "data"),
    InfraEdge("2africa", "SA", 0.35, "data"),

    # Port → Country dependencies
    InfraEdge("ras_tanura", "SA", 0.90, "oil_export"),
    InfraEdge("shanghai", "CN", 0.70, "trade"),
    InfraEdge("rotterdam", "DE", 0.60, "trade"),
    InfraEdge("singapore", "SG", 0.85, "trade"),
    InfraEdge("busan", "KR", 0.70, "trade"),
]


# ─────────────────────────────────────────────────────────────────────
# Infrastructure Graph
# ─────────────────────────────────────────────────────────────────────

class InfrastructureGraph:
    """Dependency graph for infrastructure cascade modeling.

    Supports disruption simulation via BFS propagation (max depth 3).
    """

    def __init__(self):
        self._nodes: dict[str, InfraNode] = {}
        self._adjacency: dict[str, list[InfraEdge]] = {}
        self._build_graph()

    def _build_graph(self):
        """Build graph from curated infrastructure data."""
        # Register all nodes
        for collection in [CHOKEPOINTS, PORTS, PIPELINES, CABLES, COUNTRY_NODES]:
            for node_id, node in collection.items():
                self._nodes[node_id] = node
                if node_id not in self._adjacency:
                    self._adjacency[node_id] = []

        # Register edges
        for edge in EDGES:
            if edge.source_id not in self._adjacency:
                self._adjacency[edge.source_id] = []
            self._adjacency[edge.source_id].append(edge)

    def get_node(self, node_id: str) -> InfraNode | None:
        return self._nodes.get(node_id)

    @property
    def node_count(self) -> int:
        return len(self._nodes)

    @property
    def edge_count(self) -> int:
        return sum(len(edges) for edges in self._adjacency.values())

    def simulate_disruption(
        self,
        node_id: str,
        disruption_level: float = 1.0,
        max_depth: int = 3,
    ) -> CascadeAlert | None:
        """Simulate disruption at a node and propagate through dependencies.

        disruption_level: 0.0 (no disruption) to 1.0 (total shutdown)
        max_depth: BFS propagation depth limit

        Returns CascadeAlert with all affected nodes and countries.
        """
        if node_id not in self._nodes:
            return None

        trigger = self._nodes[node_id]
        affected: dict[str, float] = {}  # node_id → impact strength
        visited: set[str] = {node_id}
        queue: list[tuple[str, float, int]] = [(node_id, disruption_level, 0)]

        while queue:
            current_id, current_strength, depth = queue.pop(0)
            if depth >= max_depth:
                continue

            for edge in self._adjacency.get(current_id, []):
                target_id = edge.target_id
                if target_id in visited:
                    continue

                target_node = self._nodes.get(target_id)
                if not target_node:
                    continue

                # Impact: edge_weight × disruption_level × (1 - redundancy)
                impact = edge.weight * current_strength * (1.0 - target_node.redundancy)

                if impact < 0.05:
                    continue  # negligible impact, stop propagation

                affected[target_id] = max(affected.get(target_id, 0.0), round(impact, 3))
                visited.add(target_id)
                queue.append((target_id, impact, depth + 1))

        if not affected:
            return None

        # Extract affected countries
        affected_countries = [
            nid for nid, node in self._nodes.items()
            if nid in affected and node.node_type == NodeType.COUNTRY
        ]

        total_impact = sum(affected.values())

        # Build summary
        top_affected = sorted(affected.items(), key=lambda x: x[1], reverse=True)[:5]
        summary_parts = []
        for nid, impact in top_affected:
            node = self._nodes[nid]
            summary_parts.append(f"{node.name}: {impact:.0%} impact")

        summary = f"Disruption at {trigger.name} ({disruption_level:.0%} level) cascades to {len(affected)} nodes. " \
                  f"Top impacts: {'; '.join(summary_parts)}"

        alert = CascadeAlert(
            trigger_node=node_id,
            affected_nodes=list(affected.keys()),
            max_depth=max_depth,
            total_impact=round(total_impact, 2),
            summary=summary,
            affected_countries=affected_countries,
        )

        logger.info("[InfraCascade] %s", summary)
        return alert

    def find_nearest_infrastructure(
        self,
        event_text: str,
    ) -> list[tuple[str, InfraNode]]:
        """Find infrastructure nodes mentioned in event text (keyword match).

        Returns list of (node_id, node) matches.
        """
        text_lower = event_text.lower()
        matches = []

        for node_id, node in self._nodes.items():
            # Check node name keywords
            name_words = node.name.lower().split()
            for word in name_words:
                if len(word) >= 4 and word in text_lower:
                    matches.append((node_id, node))
                    break

        return matches

    def get_chokepoint_dependencies(self, chokepoint_id: str) -> list[dict]:
        """Get all downstream dependencies of a chokepoint."""
        result = []
        for edge in self._adjacency.get(chokepoint_id, []):
            target = self._nodes.get(edge.target_id)
            if target:
                result.append({
                    "target": target.name,
                    "target_type": target.node_type.value,
                    "dependency_weight": edge.weight,
                    "dependency_type": edge.dependency_type,
                    "redundancy": target.redundancy,
                })
        return result


# Module-level singleton
_graph: InfrastructureGraph | None = None


def get_infrastructure_graph() -> InfrastructureGraph:
    """Get or create the infrastructure graph singleton."""
    global _graph
    if _graph is None:
        _graph = InfrastructureGraph()
    return _graph
